### ISSUE TITLE
Support keyboard navigation

### ISSUE THREAD

**Issue by angelos** [dvberkel/2016-wishes#1]
Clicking left and right like mad
Keyboard navigation would make me glad
As you all can plainly see
These puzzles are just too hard for me

**Comment by dvberkel** [comment]
Even though I am not well versed
In meter and rhyme so this will be terse
I will work on your request and get back to you soon
In the meantime just remember, there is no spoon

**Comment by dvberkel** [comment]
@angelos. you can rest easy
Do not let the added functionality make you queasy
Use awsd to move the blank tile
Soon you will solve the puzzle with hacker style

**Comment by angelos** [comment]
With Aay, Double-You, Dee and Ess,
More precious minutes wasted, alas
My new year started right on clue,
And all the best to all of you!
